name: calendar_alarm
description: "variable calendar notification"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.14.0
  firebase_analytics: ^10.8.0
  firebase_auth: ^4.16.0
  firebase_auth_oauth: ^1.2.2
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.9
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.3.0
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  google_sign_in: ^6.2.1
  googleapis: ^12.0.0
  googleapis_auth: ^1.4.1
  http: ^0.13.0
  in_app_purchase: ^3.1.12
  pedantic_mono: ^1.25.0
  scrollable_positioned_list: ^0.3.8
  sign_in_button: ^3.2.0
  sign_in_with_apple: ^5.0.0
  table_calendar: ^3.0.9
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
    - assets/img/onboard-background.png
    - assets/img/logo-android.png
    - assets/img/logo-ios.png
    - assets/img/logo-argon.png
    - assets/img/profile-screen-avatar.jpg
    - assets/img/profile-screen-bg.png
    - assets/img/register-bg.png
    - assets/img/chat-avatar.jpeg
    - assets/img/argon-logo.png

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 200
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 600
