name: Flutter CI

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build:
    runs-on: blacksmith-4vcpu-ubuntu-2404

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup asdf
        uses: asdf-vm/actions/setup@v1

      - name: Install asdf plugins
        run: |
          asdf plugin add ruby
          asdf plugin add flutter
          asdf plugin add dart

      - name: Install runtime versions
        run: asdf install

      - name: Install dependencies
        run: flutter pub get

      - name: Run Flutter tests
        run: flutter test

      - name: Run Flutter Lint
        run: flutter analyze

      - name: Build Flutter Android app
        run: flutter build apk

      - name: Setup CocoaPods
        run: sudo gem install cocoapods

      - name: Install CocoaPods dependencies
        run: cd ios && pod install

      - name: Build Flutter iOS app
        run: flutter build ios --release --no-codesign

      - name: Build Flutter macOS app
        run: flutter build macos --release
